apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        envFrom:
          - configMapRef:
              name: mysql-k8s-configmap
          - secretRef:
              name: mysql-k8s-secret
              key: MYSQL_ROOT_PASSWORD # to use a single secret to avail all of them do not put 'key'
        ports:
        - containerPort: 3306
          name: mysql
        resources:
           limits:
             cpu: 1
             memory: 1Gi
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
