apiVersion: v1
kind: Pod
metadata:
  name: spring-k8s-pod
  labels:
    app: backend
spec:
  containers:
    - name: spring-k8s
      image: spring-k8s:1.0
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
      imagePullPolicy: Always
