apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s-deploy
  labels:
    app: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       - name: spring-k8s
         image: spring-k8s:1.0
         ports:
          - containerPort: 8080
         resources:
           limits:
             cpu: 1
             memory: 2Gi
           requests:
             cpu: 1
             memory: 2Gi
         imagePullPolicy: Always
