name: together CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created
      - published

jobs:
  build:

    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build backend
        working-directory: ./demo/backend
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub
        working-directory: ./demo/backend
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.5.0
        with:
          context: $GITHUB_WORKSPACE/demo/backend/Dockerfile
          tags: avijitmondal/kubernetes-tutorial/backend:latest
          github-token: ${{ github.token }}
